# Generated by Django 5.1 on 2024-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
