# Generated by Django 5.1 on 2024-11-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_address'),
        ('store', '0003_cartitem'),
    ]

    operations = [
    ]
