# Generated by Django 5.1 on 2024-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_dilivery_ref_order_pay_refrence_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delivered', 'delivered'), ('deleted', 'Deleted')], default='unpaid', max_length=20),
        ),
    ]
