# Generated by Django 5.1 on 2024-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/profiles/avatar1.png', upload_to='uploads/profiles/'),
        ),
    ]
